name: "Setup test env"
description: "Setup test environment for actions"

inputs:
  node-version:
    description: "Node version"
    required: false
    default: "20"

runs:
  using: "composite"
  steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: "yarn"
    
    - name: "Install dependencies"
      shell: "bash"
      run: yarn install --immutable

    - name: Install dev cli
      shell: "bash"
      run: sudo npm i -g medusa-dev-cli

    - name: Set path to medusa repo
      shell: "bash"
      run: medusa-dev --set-path-to-repo $(pwd)
