# Checks for outdated documentation content and sends notification about it
name: Docs Freshness Check
on:
  schedule:
    - cron: "0 0 1 * *" # once a month

jobs:
  freshness-check:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.REFERENCE_PAT }}
      LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "21.1.0"
          cache: "yarn"

      - name: Install dependencies
        uses: ./.github/actions/cache-deps
        with:
          extension: docs-freshness-check

      - name: Install Workspace dependencies
        run: yarn install
        working-directory: docs-util

      - name: Perform Freshness Check
        run: yarn check:freshness
        working-directory: docs-util/packages/scripts
