name: Retrieve Traffic Analytics
on: 
  schedule:
    - cron: '0 0 * * *'
jobs:
  traffic:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.REFERENCE_PAT }}
      SEGMENT_API_KEY: ${{ secrets.SEGMENT_API_KEY }}
      DEBUG: false
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "14"
          cache: "yarn"

      - name: Install dependencies
        uses: ./.github/actions/cache-deps
        with:
          extension: docs

      - name: Retrieve Analytics
        run: |
          node ./scripts/gh-analytics.js
